// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxekfggobnqkarwnfswo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4ZWtmZ2dvYm5xa2Fyd25mc3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjA2MjAsImV4cCI6MjA2Nzg5NjYyMH0.YZqPNbENGx_WgVBFCJKllRnqlJt6k_g80vm1Cnepwq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});